CREATE DATABASE ecommerce;
USE ecommerce;
CREATE TABLE ecom(
Order_ID	VARCHAR(50)	PRIMARY KEY,
Order_Date	DATE	NOT NULL,
Customer_Name	VARCHAR(100) NOT NULL,
Region	VARCHAR(50)	NOT NULL,
Product_Name	VARCHAR(100) NOT NULL,
Category	VARCHAR(50)	NOT NULL,
Quantity	INT	NOT NULL,
Unit_Price	NUMERIC(10,2) NOT NULL,
Discount 	INT	NOT NULL,
Total_Revenue	NUMERIC(10,2)	NOT NULL,
Profit	NUMERIC(10,2)	NOT NULL,
Ship_Mode	VARCHAR(50)	NOT NULL
);
#--How can we view all the records available in the e-commerce dataset?
SELECT * FROM ecom;
#--Which product categories generate the highest total profit?
SELECT Category, SUM(Profit) AS Profit 
FROM ecom 
GROUP BY Category
ORDER BY Profit DESC;
#--What is the second-highest profit value in the dataset?
SELECT MAX(Profit) FROM ecom 
WHERE Profit<(SELECT MAX(Profit) FROM ecom);
#--What is the average profit generated by each region?
SELECT Region, AVG(Profit) AS Average
FROM ecom
GROUP BY Region;
#---Which customers generate the highest sales, and how do their average profit, quantity, and total discount compare?
SELECT Customer_Name,
SUM(Total_Revenue) AS Sales, 
AVG(Profit) AS  Average_Profit, 
COUNT(Quantity) AS Count_of_Quantity,
SUM(Discount) AS Total_Discount
FROM ecom 
GROUP BY Customer_Name
ORDER BY Sales DESC;
#--Are there any missing customer names in the dataset?
SELECT Customer_Name
FROM ecom
WHERE Customer_Name IS NULL;
#--How do sales, average profit, quantity, and discounts compare between the North and Central regions?
SELECT Region, SUM(Total_Revenue) AS Sales, 
AVG(Profit) AS  Average_Profit, 
COUNT(Quantity) AS Count_of_Quantity,
SUM(Discount) AS Total_Discount
FROM ecom
WHERE Region IN ('North','Central')
GROUP BY Region;
#--Who are the top 5 customers based on total sales?
SELECT Customer_Name, 
 SUM(Total_Revenue) AS Sales, 
AVG(Profit) AS  Average_Profit, 
SUM(Discount) AS Total_Discount
FROM ecom
GROUP BY Customer_Name
ORDER BY Sales DESC
LIMIT 5;
#--Which customers have names starting with the letter 'D'?
SELECT Customer_Name
FROM ecom
WHERE Customer_Name LIKE 'd%';
#--Which customers generated total revenue between 50 and 100, and which of them generated the highest revenue?
SELECT Customer_Name, SUM(Total_Revenue) AS Revenue
FROM ecom
GROUP BY Customer_Name
HAVING SUM(Total_Revenue) BETWEEN 50 AND 100
ORDER BY Revenue DESC
LIMIT 5;

